services:
  datastorage1:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          config: config-1
          portone: 8080
          porttwo: 8090
    ports:
      - "8080:8080"  
      - "8090:8090"
  datastorage2:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          config: config-2
          portone: 8081
          porttwo: 8091
    ports:
      - "8081:8081"  
      - "8091:8091" 
  datastorage3:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
          config: config-3
          portone: 8082
          porttwo: 8092
    ports:
      - "8082:8082"  
      - "8092:8092" 
networks:
  default:
    name: datastore